name: CI Restaurant Reservation System

on:
    push:
        branches: [ main, dev ]
    pull_request:
        branches: [ main, dev ]

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Instalar Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'npm'
                cache-dependency-path: backend/package-lock.json

            - name: Instalar dependencias con npm ci
              run: npm ci
              working-directory: backend
            - name: Correr eslint
              run: npm run lint
              working-directory: backend
            - name: Formatear codigo
              run: npm run format:check
              working-directory: backend
            - name: Correr tests
              run: npm run test
              working-directory: backend